sudo: required
services:
    - docker

before_install:
    - docker build -t sumro/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sumro/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-322042565622"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


